/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsa;

import java.io.DataOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.math.BigInteger;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author bocal
 */
public class VCliente extends javax.swing.JFrame {

    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        msj = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cifrar = new javax.swing.JButton();
        txtPrimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RSA Serializado feo");
        setResizable(false);

        jLabel1.setText("Vista del Cliente");

        jLabel2.setText("Ingrese el mensaje a cifrar");

        msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msjActionPerformed(evt);
            }
        });

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane1.setViewportView(salida);

        jLabel3.setText("Datos enviados");

        cifrar.setText("Enviar");
        cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifrarActionPerformed(evt);
            }
        });

        txtPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimoActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingrese el tamaño del primo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msj)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cifrar)
                        .addGap(204, 204, 204))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(msj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cifrar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msjActionPerformed

    private void cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifrarActionPerformed
        
        int tamPrimo;
        BigInteger p,q,n;
        BigInteger phi;
        BigInteger e,d;
        BigInteger[] encriptado;
        String mensaje;
   
        mensaje=msj.getText();
        String tamPrimoS=txtPrimo.getText();
        
        Validar val = new Validar();
        boolean check= val.letras(mensaje);
        String todo;
        
        if (check==true && mensaje.length()>0 && mensaje.length()<100 && tamPrimoS.length()<3) {
            
            try{
                
                tamPrimo=Integer.parseInt(tamPrimoS);
                
                Socket skCliente = new Socket ("25.9.47.77",5000);
                System.out.println(skCliente.getLocalAddress()+" " +skCliente.getInetAddress());
                todo="Dirección del servidor: "+skCliente.getInetAddress();
                
                RSA rsa = new RSA(tamPrimo);
                
                OutputStream os= skCliente.getOutputStream();
                DataOutputStream flujo = new DataOutputStream(os);
                
                p=rsa.damep();
                String S=""+p;
                System.out.println("P calculada: "+S);
                
                todo=todo+"\np: "+S;
                q=rsa.dameq();
                String qS=""+q;
                System.out.println("Q calculada: "+qS);
                
                todo=todo+"\nq: "+qS;
                n=rsa.damen();
                String nS=""+n;
                System.out.println("N calculada: "+nS);
                
                todo=todo+"\np: "+nS;
                flujo.writeUTF(S);
                flujo.writeUTF(qS);
                flujo.writeUTF(nS);
                System.out.println("Phi calculada: "+rsa.damephi());
                flujo.writeUTF(""+rsa.damee());
                
                encriptado=rsa.encriptar(mensaje);
                int tammen=encriptado.length;
                flujo.write(tammen);
                System.out.println(tammen);


                System.out.println("e calculada: "+rsa.damee() );
                todo=todo+"\ne: "+rsa.damee();
                System.out.println("d calculada: "+rsa.damed());
                todo=todo+"\nmensaje encriptado: ";
                
                for (BigInteger encriptado1 : encriptado) {
                    String enc = encriptado1.toString();
                    System.out.println(enc);
                    todo=todo+enc;
                    flujo.writeUTF(enc);
                }
                
                salida.setText(todo);
                
                skCliente.close();
            }catch (IOException es){
                JOptionPane.showMessageDialog(null, "Inicializa el servidor antes de ingresar tu mensaje");
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Ingresa en el mensaje unicamente numeros, no mayor a 100 caracteres\nIngresa en el tamaño del primo un numero entero no mayor igual a 100");
            System.out.println("Ingresa unicamente numeros");
        }
        
    
    }//GEN-LAST:event_cifrarActionPerformed

    private void txtPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField msj;
    private javax.swing.JTextArea salida;
    private javax.swing.JTextField txtPrimo;
    // End of variables declaration//GEN-END:variables
}
